
import type { Metadata } from 'next'
 
import 'bootstrap/dist/css/bootstrap.min.css';

import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from "@fortawesome/fontawesome-svg-core";

import './globals.css'
 
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Food Delivery Service',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} >{children}</body>
    </html>
  )
}
